### ISSUE TITLE
Stopped working - Wont initialise switch 

### ISSUE THREAD

**Issue by gdotp01** [nitaybz/homebridge-delay-switch#24]
Hi,
I hope you can help. I've been using this plugin for over a year to set a timer every 15 mins so that I  can turn my pond fountain off if the wind is too high.  Yesterday however I tried to install the IFFT plugin to get round the current issue with the authentication method changing for Blink cameras. However I now get the following error as soon as any switch is initialised 

[5/8/2020, 10:47:00 AM] TypeError: Cannot read property 'hap' of undefined
    at new delaySwitch (/opt/nodejs/lib/node_modules/homebridge-delay-switch/index.js:13:23)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)

The JSOn is simple (default) and has worked until yesterday.

{
         "accessory": "DelaySwitch",
         "name": "DelaySwitch",
         "disableSensor": false,
         "delay": 1000
        }

I'm on homebridge-delay-switch v2.1.2

**Comment by nitaybz** [comment]
what is your homebridge version?

**Comment by gdotp01** [comment]
That worked. I updated to the latest version and its working again. Thanks
